github.com:
    users:
        dffdfddd:
            oauth_token: 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
        soltanmemmedov123-ui:
            oauth_token: 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
    git_protocol: https
    user: soltanmemmedov123-ui
    oauth_token: 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
